title: "Companion 導入ガイド"
summary: "Bitfocus Companion ハンズオン"
topics: ["tech", "Companion", "StreamDeck"]
# topic_depth: 1
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 01_about
  - 02_links
  - 03_install
  - 04_gui
  - 05_add_connection
  - 06_add_button
  - 07_review_setting
  - 08_change_button_face
  - 09_variables
  - 10_add_action
  - 11_feedback
  - 12_toggle_button
  - 13_change_image
  - 14_idk_switcher
  - 15_panasonic_camera
  - 16_emulator
  - 17_remote
  - 18_selector1
  - 18_selector2
  - 18_selector3
  - 18_selector4
